import Head from "next/head";
import React, { useState } from 'react';

import Image from "next/image";
import estilos from "../styles/Home.module.css";

import Logo from "../../public/assets/barbearia-logo.png";
import imgEscuro from "../../public/assets/moon.png";
import imgClaro from "../../public/assets/sun.png";

var imagemTema = imgEscuro;
var darkLight = "Dark";
var logoTema = estilos.logo_claro;

export default function Home() {
    const modoEscuro = 'modo-escuro';
    const modoClaro = 'modo-claro';
    
    const [ novaCor, setNovaCor ] = useState(modoClaro);
    const [estiloAtualizado, setEstiloAtualizado] = useState(true);
    
    const alterarCor = () => {
      
        if (estiloAtualizado === true) {
            setEstiloAtualizado(false);
            setNovaCor(modoClaro);
            imagemTema = imgEscuro;
            darkLight = "Dark";
            logoTema = estilos.logo_claro;
        } else {
            setEstiloAtualizado(true);
            setNovaCor(modoEscuro);
            imagemTema = imgClaro;
            darkLight = "Light";
            logoTema = estilos.logo_escuro;
        }
    }

    return (
    <div className={novaCor}>
      <Head>
        <title>BarberShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
     
      <div className={estilos.topo}>
        <Image className={logoTema} src={Logo} alt="logomarca"/>
        <button onClick={alterarCor} className={estilos.botao}><Image className={estilos.img_tema} src={imagemTema} alt="logomarca"/>{darkLight}</button>
      </div>

      <section className={estilos.secao_banner}></section>

      <section className={estilos.secao_texto}>
        <div className={estilos.limitar}>
          <h1 className={estilos.titulo}>Bem-vindo a Barber Shop</h1>
          <p className={estilos.primeiro_paragrafo}>Nossa barbearia sempre oferece profissionais de qualidade e estamos prontos para lidar com suas maiores expectativas.</p>
          <p className={estilos.segundo_paragrafo}>Nossos serviços são dedicados ao seu sucesso pessoal. Aqui temos uma equipe premiada que demonstrou o talento de mestres barbeiros em vários concursos de estilo. Deixe nosso barbeiro ser seu estilista pessoal e você nunca ficará desapontado.</p>
          <p className={estilos.assinatura}>S. Kelly</p>
        </div>
      </section>
    </div>
  );
}